name: objectory
version: 0.1.0
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: Object document mapper/persistency layer for server-side and browser apps
homepage: https://github.com/vadimtsushko/objectory
dependencies:
  unittest: any
  mongo_dart: 
    git: git://github.com/vadimtsushko/mongo_dart
  args: any
  browser: any
  logging: any
