name: objectory
description: Object document mapper/persistency layer for server-side and browser apps
author: Vadim Tsushko <vadimtsushko@gmail.com>
homepage: https://github.com/vadimtsushko/objectory
version: 0.0.6
dependencies:
 unittest: any
 logging: any  
 args: any  
 mongo_dart: any     
 lawndart: any