name: objectory
version: 0.3.14-dev
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: Object document mapper/persistency layer for server-side and browser apps
homepage: https://github.com/vadimtsushko/objectory
dependencies:
  browser: any
  logging: any
  mongo_dart: any
  mongo_dart_query: any
dev_dependencies:
  args: any
  hop: any
  stream: any
  unittest: any
