name: objectory
version: 0.2.2
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: Object document mapper/persistency layer for server-side and browser apps
homepage: https://github.com/vadimtsushko/objectory
dependencies:
  mongo_dart: any
  args: any
  browser: any
  logging: any
dev_dependencies:
  unittest: any
